// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bhjwdccmbmxudyvllsfu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJoandkY2NtYm14dWR5dmxsc2Z1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgxNDM0MzEsImV4cCI6MjA3MzcxOTQzMX0.E23yaSbiSxJ3hB43S3peYSubvPP60frt047wjBysres";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});